### ISSUE TITLE
Add menu item for access to cite page

### ISSUE THREAD

**Issue by Klap-in** [tatewake/dokuwiki-plugin-cite#2]
Please see https://www.dokuwiki.org/devel:menus
(especially the referred page: https://www.patreon.com/posts/menus-14160215)

**Comment by tatewake** [comment]
Hi @Klap-in , sorry for the delay on responding to your issue.

Although I'd like to support the new DokuWiki "menus" feature, I don't think I'll be able to as I don't understand what would need to be changed for this integration to work.

If you or someone else would like to add support (via some code commits / pull requests) and can demonstrate them working, I'll gladly accept the PR and add support.

Otherwise, I'll close this ticket for now.

Thanks!
